### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by gustavoguichard** [seasonedcc/development-of-composable-functions#9]
## Internal testing (long version)
- [x] Bring cf to Remaster
  - [x] Bring remix-forms to Remaster 🚩
  - [x] Use composable-functions into remix-forms 🚩
  - [x] Use composable-functions in every app and package of Remaster mono-repo
- [x] Develop new Framework with cf

## Documentation
- [x] Update README
- [x] Update JSDocs

## Best effort to help migration
- [x] ~export `compat` module as a separate entry: `import { serialize } from "composable-functions/compat"`~ giving up on compat since we have renamed the lib allowing incremental migration
- [x] ~normalize type exports in `compat` module~
- [x] ~normalize function exports in `compat` module~
- [x] Migration & Incremental migration guide

## Improvements (may change with internal testing)
- [x] More tests for cf (we have enough of df tests)
- [x] Discussion about semantics: domain, environment, fromSuccess, what is a DF?
- [x] Adventure into `collect` types 🚩
- [x] Adventure into `collectSequence` types - may be herculean due to the order of Record keys not behaving the same as ECMAScript. It could be df-only 🚩
- [x] Simplify DF combinators implementation based on CF
- [x] Implement `branch` 🚩

**Comment by gustavoguichard** [comment]
We should also think about how to make recursions with CF =)
